name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC+7 (7 hours ahead of UTC)
    - cron: '0 17 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: "False"
          CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LOC_CHART: "False"
          SHOW_OS: "False"
          SYMBOL_VERSION: 3
          LOCALE: "en"
          
